//! FlowLog Parser Library
//!
//! This crate provides parsing capabilities for FlowLog, a logic programming language.
//! It includes modules for handling different language constructs such as aggregations,
//! arithmetic expressions, comparisons, declarations, heads, and complete rules.
//!
//! The parser is built using the Pest parsing expression grammar (PEG) library,
//! which provides fast and reliable parsing with clear error messages.
//!
//! # Example
//! ```rust
//! use parsing::{FlowLogParser, Rule, Parser};
//!
//! // Parse a simple FlowLog expression
//! let input = "person(john, 25)";
//! let parsed = FlowLogParser::parse(Rule::head, input).unwrap();
//! ```

// Module declarations - each module handles a specific aspect of FlowLog syntax
pub mod aggregation; // Aggregation functions (sum, max, min, count)
pub mod arithmetic; // Arithmetic expressions and operations
pub mod compare; // Comparison operations (>, <, =, !=, etc.)
pub mod decl; // Variable and predicate declarations
pub mod diagnostic; // The one shape every refusal takes
pub mod embedded; // Rust implementations embedded in a .dl program
pub mod head; // Head expressions in logic rules
pub mod parser; // Core parsing utilities and traits
pub mod rule; // Complete rule definitions and structures
pub mod validate; // Well-formedness checks the grammar cannot express

// External crate imports
extern crate pest; // Pest parsing expression grammar library

#[macro_use]
extern crate pest_derive; // Derive macros for generating parsers

// Public re-exports for convenient access to commonly used types
pub use pest::{
    iterators::Pair, // Represents a matched rule with its position in the source
    Parser,          // Trait for parser implementations
};

/// The value domain of FlowLog's `number` type.
///
/// Every scalar in the engine is one `Val`: an integer constant in a program,
/// a cell of an input file, a column of a physical row, an aggregate result,
/// and an argument or result of an embedded `@call`. The alias exists so that
/// the parser, the physical row representation and the native call ABI cannot
/// drift apart; it is defined here because `parsing` is the crate every other
/// crate in the workspace depends on.
///
/// 64 bits is the standard signed domain for a Datalog engine (Souffle's
/// `RamSigned` is `int64_t`). Workloads that FlowLog targets - program
/// analysis facts, hashes, addresses, identifiers minted by hashing - do not
/// fit in 32 bits, and a value that does not fit is a wrong answer rather than
/// an error.
pub type Val = i64;

/// The main parser struct for FlowLog language constructs.
///
/// This parser is automatically generated by the `pest_derive` macro based on
/// the grammar definition in `grammar.pest`. It can parse various FlowLog
/// constructs including rules, heads, arithmetic expressions, aggregations,
/// and comparisons.
///
/// # Grammar File
/// The parser grammar is defined in `./grammar.pest` which specifies the
/// syntax rules for the FlowLog language.
///
/// # Usage
/// ```rust
/// use parsing::{FlowLogParser, Rule, Parser};
///
/// let input = "result(x + y) :- input(x), input(y).";
/// let pairs = FlowLogParser::parse(Rule::rule, input).unwrap();
/// ```
#[derive(Parser)]
#[grammar = "./grammar.pest"]
pub struct FlowLogParser;
